#!/bin/sh /etc/rc.common

START=99
STOP=10

restart() {
    (crontab -l 2>/dev/null | sed '/poddns/d') | crontab -
    if [ $(uci -q get poddns.config.enable) = 1 ]; then
        (crontab -l 2>/dev/null; echo "* */5 * * * /usr/share/poddns/check.sh") | crontab -
    fi
}